flowchart TD
%% generated in 0.01s
    examples__llm["examples.llm<br/>5 funcs"]
    examples__mcp["examples.mcp<br/>2 funcs"]
    sumd__cli["sumd.cli<br/>29 funcs"]
    sumd__cli_doql["sumd.cli_doql<br/>6 funcs"]
    sumd__cli_scan["sumd.cli_scan<br/>14 funcs"]
    sumd__cqrs["sumd.cqrs<br/>74 funcs"]
    sumd__dsl["sumd.dsl<br/>179 funcs"]
    sumd__extractor["sumd.extractor<br/>63 funcs"]
    sumd__mcp_server["sumd.mcp_server<br/>18 funcs"]
    sumd__parser["sumd.parser<br/>9 funcs"]
    sumd__pipeline["sumd.pipeline<br/>16 funcs"]
    sumd__toon_parser["sumd.toon_parser<br/>9 funcs"]
    sumd__validator["sumd.validator<br/>16 funcs"]
    test["test<br/>1 funcs"]
    sumd__dsl ==>|42| test
    examples__mcp ==>|31| test
    sumd__pipeline ==>|20| sumd__extractor
    examples__llm ==>|11| test
    sumd__mcp_server ==>|6| sumd__parser
    sumd__toon_parser ==>|4| sumd__dsl
    sumd__cli ==>|4| sumd__parser
    sumd__cli ==>|4| sumd__cli_scan
    sumd__cqrs ==>|4| sumd__parser
    sumd__cqrs ==>|4| sumd__extractor
    sumd__dsl -->|3| sumd__parser
    examples__llm -->|2| sumd__parser
    sumd__cli_scan -->|2| sumd__cli_doql
    sumd__cli_scan -->|2| sumd__extractor
    sumd__cqrs -->|2| sumd__validator
    sumd__validator -->|1| sumd__extractor
    sumd__cli -->|1| sumd__validator
    sumd__cli -->|1| sumd__extractor
    sumd__extractor -->|1| sumd__toon_parser
    sumd__cli_scan -->|1| sumd__validator
    sumd__cli_scan -->|1| sumd__parser
    sumd__cli_doql -->|1| sumd__extractor
    sumd__pipeline -->|1| sumd__toon_parser
    sumd__dsl -->|1| sumd__extractor
    sumd__dsl -->|1| sumd__validator
